<a href="https://colab.research.google.com/github/Surajpatel2003/ADS-Lab/blob/main/Suraj_ADS_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**AIM :** Explore the descriptive and inferential statistics on the given dataset.

## **Step - 1 : Data Collection**

**a. Download the Datasets from Kaggle / UCI Repository**
1. [Customer Segmentation Dataset from Kaggle](https://www.kaggle.com/code/fabiendaniel/customer-segmentation/input)
2. [Credit Card Fraud Detection Dataset from Kaggle](https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud)

**b. Create Dataset for the following:**
- - 360 degree Student Portfolio Dataset
- - - ***For example***: Username, Name,	Division,	Roll No, Age, Gender,	Date of Birth,	Address, Contact No, 10th %,	12th %,	CGPA,	Disability,	Further Preference: Job / Higher Studies,	Technical Skills : Java,	Python,	DSA,	OS,	DBMS,	Communication,skills,	Presentation skills,	Creativity :	Singing,	Dance,	Number of internships,	Number of certification courses,	Name of the certification courses,	Member of a technical society,	Member of Non Technical society
-- Student feedback

**Courtesy** :
* About Loan Dataset : Dream Housing Finance company deals in all home loans. They have presence across all urban, semi urban and rural areas. Customer first apply for home loan after that company validates the customer eligibility for loan.
* [Loan Data set from Kaggle](https://www.kaggle.com/datasets/burak3ergun/loan-data-set?resource=download)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np
import statistics
import seaborn as sns

In [ ]:
df = pd.read_csv("loan_data_set.csv")

In [ ]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

## **Step - 2 : Perform Descriptive Analysis**

**Descriptive Statistics**
* focuses on describing and summarizing the main features of a data set.
* used to organize, display, and interpret numerical and categorical data.
* includes measures of central tendency, such as mean, median, and mode, which describe the typical value or center of a data set.
* It also includes measures of variability, such as range, variance, and standard deviation, which describe how spread out the data is.
* used to describe the distribution of a data set, such as whether it is symmetrical or skewed.
* also be used to identify any outliers or unusual observations in the data.
* used in various fields, such as business, medicine, social sciences, and more, to understand and analyze data.
* describes the characteristics of a data set.
* It is a simple technique to describe, show and summarize data in a meaningful way.
* involves taking a potentially sizable number of data points in the sample data and reducing them to certain meaningful summary values and graphs.
* The process allows you to obtain **insights and visualize the data.**

**Descriptive Statistics Measures**
1. Distribution :
- shows us the frequency of different outcomes (or data points) in a population or sample.
- We can show it as numbers in a list or table, or we can represent it graphically.
2. Central tendency
- Common measures of central tendency include:
- - **mean**: average value of all the data points.
- - **median**: central or middle value in the dataset.
- - **mode**: value that appears most often in the dataset.
3. Variability
- Common measures of variability include:
- - **Standard deviation** shows us the amount of variation or dispersion.
- - - Low standard deviation ==> most values are close to the mean.
- - - High standard deviation ==> the values are more broadly spread out.
- - **Minimum** and **maximum** values are the highest and lowest values in a dataset or quartile.
- - **Range** measures the size of the distribution of values.
- - - This can be easily determined by subtracting the smallest value from the largest.
- - **Kurtosis**: measures whether or not the tails of a given distribution contain extreme values (also known as **outliers**).
- - - If a tail lacks outliers ==> low kurtosis.
- - - If a dataset has a lot of outliers ==> high kurtosis.
4. Skewness: measure of a datasets symmetry.
- If you were to plot a bell-curve and the right-hand tail was longer and fatter ==> positive skewness. \
- If the left-hand tail is longer and fatter ==> negative skewness.

In [ ]:
df.shape

(614, 13)

In [ ]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [ ]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ApplicantIncome,614.0,5403.459283,6109.041673,150.0,2877.5,3812.5,5795.00,81000.0
CoapplicantIncome,614.0,1621.245798,2926.248369,0.0,0.0,1188.5,2297.25,41667.0
LoanAmount,592.0,146.412162,85.587325,9.0,100.0,128.0,168.00,700.0
Loan_Amount_Term,600.0,342.000000,65.120410,12.0,360.0,360.0,360.00,480.0
Credit_History,564.0,0.842199,0.364878,0.0,1.0,1.0,1.00,1.0

In [ ]:
df.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [ ]:
df.mean()

<ipython-input-16-c61f0c8f89b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()

ApplicantIncome      5403.459283
CoapplicantIncome    1621.245798
LoanAmount            146.412162
Loan_Amount_Term      342.000000
Credit_History          0.842199
dtype: float64

## **Step - 3: Perform Inferential Analysis**

**Inferential statistics**
- focus on making generalizations about a larger population based on a representative sample of that population.
- focuses on making predictions (rather than stating facts) its results are usually in the form of a probability.
- helps to draw conclusions and make predictions based on a data set. It is done using several techniques, methods, and types of calculations.
- Some of the most important types of inferential statistics calculations are:
1. Regression Analysis
- show the relationship between a set of independent variables and a dependent variable.
- predict the value of the dependent variable based on different values of the independent variables.
2. Hypothesis tests
- to determine whether the relationships observed in sample data actually exist in the data set.